runtime: go
api_version: go1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules

handlers:

- url: /(view|history|edit|save|delete)/(.*)
  script: _go_app

- url: /user/(login|logout)
  script: _go_app

- url: /
  script: _go_app

- url: /search
  script: _go_app

- url: /(.+)\.(.+)
  static_files: static/\1.\2
  upload: static/.*\..*
